<?php

$arrayConsultas = array(
  ['inf_casas', 'id!=""', '(General - ADM)', 'Viviendas'],
  ['inf_casas', 'responsable="0"', '(General - ADM)', 'Viviendas inhabitadas'],
  ['inf_casas', 'tipo="Casa"', '(General)', 'Casas'],
  ['inf_casas', 'tipo="Rancho"', '(General)', 'Ranchos'],
  ['inf_casas', 'tipo="Edificio"', '(General)', 'Edificios'],
  ['inf_casas', 'condicion_vivienda="Propia"', '(Propiedad de la vivienda)', 'Propia'],
  ['inf_casas', 'condicion_vivienda="Alquilada"', '(Propiedad de la vivienda)', 'Alquilada'],
  ['inf_casas', 'condicion_vivienda="Prestada"', '(Propiedad de la vivienda)', 'Prestada'],
  ['inf_casas', 'condicion_vivienda="residencias"', '(Propiedad de la vivienda)', 'residencias'],
  ['inf_casas', 'condicion_vivienda="Invadida"', '(Propiedad de la vivienda)', 'Invadida'],
  ['inf_casas', 'condicion_vivienda="Arrimados"', '(Propiedad de la vivienda)', 'Arrimados'],
  ['inf_casas', 'zonaRiesgo="inundacion"', '(Zonas de riesgo)', 'Inundacion'],
  ['inf_casas', 'zonaRiesgo="derrumbe"', '(Zonas de riesgo)', 'Derrumbe'],
  ['inf_casas', 'zonaRiesgo="incendio"', '(Zonas de riesgo)', 'Incendio'],
  ['inf_casas', 'tenencia_tierra="Nacional (INTI)"', '(Tenencia de la tierra)', 'Nacional'],
  ['inf_casas', 'tenencia_tierra="Regional (INTU"', '(Tenencia de la tierra)', 'Regional'],
  ['inf_casas', 'tenencia_tierra="Municipal (EJIDO)"', '(Tenencia de la tierra)', 'Municipal'],
  ['inf_casas', 'vivienda_venezuela="SI"', '(Infraestructura)', 'GMVV'],
  ['inf_casas', 'bnbt="SI"', '(Infraestructura)', 'BNBT'],
  ['inf_casas', 'agua_potable="Pozo" OR agua_potable="Pozo y Tuberia"', '(Servicio de agua potable)', 'Pozo'],
  ['inf_casas', 'agua_potable="Tuberia" OR agua_potable="Pozo y Tuberia"', '(Servicio de agua potable)', 'Tubería'],
  ['inf_casas', 'agua_potable="Pozo y Tuberia"', '(Servicio de agua potable)', 'Pozo y Tuberia'],
  ['inf_casas', 'agua_potable="Algibe"', '(Servicio de agua potable)', 'Algibe'],
  ['inf_casas', 'agua_potable="Cisterna"', '(Servicio de agua potable)', 'Cisterna'],
  ['inf_casas', 'agua_potable="Del Vecino"', '(Servicio de agua potable)', 'Del vecino'],
  ['inf_casas', 'agua_potable="De la lluvia"', '(Servicio de agua potable)', 'De la lluvia'],
  ['inf_casas', 'agua_potable="Del Rio"', '(Servicio de agua potable)', 'Del Rio'],
  ['inf_casas', 'agua_potable="De la lluvia" OR agua_potable="Del Vecino" OR agua_potable="Del Rio"', '(Servicio de agua potable)', 'Sin servicio'],
  ['inf_casas', 'internet="Por Cable (CANTV)"', '(Servicio de internet)', 'Por Cable'],
  ['inf_casas', 'internet="Modem"', '(Servicio de internet)', 'Modem'],
  ['inf_casas', 'internet="Satelital"', '(Servicio de internet)', 'Satelital'],
  ['inf_casas', 'internet="Sin Servicio"', '(Servicio de internet)', 'Sin Servicio'],
  ['inf_casas', 'disposicion_basura="Servicio de Recoleccion"', '(Tratamiento de los desechos solidos)', 'Servicio de Recoleccion'],
  ['inf_casas', 'disposicion_basura="Entierro"', '(Tratamiento de los desechos solidos)', 'Entierro'],
  ['inf_casas', 'disposicion_basura="Quema"', '(Tratamiento de los desechos solidos)', 'Quema'],
  ['inf_casas', 'disposicion_basura="Al Aire Libre"', '(Tratamiento de los desechos solidos)', 'Al Aire Libre'],
  ['inf_casas', 'agua_servidas="Pozo Septico"', '(Tratamiento de aguas servidas)', 'Pozo Septico'],
  ['inf_casas', 'agua_servidas="Cloacas"', '(Tratamiento de aguas servidas)', 'Cloacas'],
  ['inf_casas', 'electricidad="Con Contrato"', '(Servicio Electrico Nacional)', 'Con Contrato'],
  ['inf_casas', 'electricidad="Sin Contrato"', '(Servicio Electrico Nacional)', 'Sin Contrato'],
  ['inf_casas', 'electricidad="Sin Electricidad"', '(Servicio Electrico Nacional)', 'Sin Electricidad'],
  ['inf_casas', 'electricidad="Con Contrato" OR electricidad="Sin Contrato"', '(Servicio Electrico Nacional)', 'Con Electricidad'],
  ['inf_casas', 'medidor_electricidad="En Funcionamiento"', '(Servicio Electrico Nacional)', 'Medidor (Funciona)'],
  ['inf_casas', 'medidor_electricidad="Danado"', '(Servicio Electrico Nacional)', 'Medidor (Dañado)'],
  ['inf_casas', 'medidor_electricidad="No Posee"', '(Servicio Electrico Nacional)', 'Sin medidor'],
  ['inf_habitantes', 'enf_renal!=""', '(Enfermedades más frecuentes)', 'E. renal'],
  ['inf_habitantes', 'diabetico!=""', '(Enfermedades más frecuentes)', 'Diabetes'],
  ['inf_habitantes', 'hipertenso!=""', '(Enfermedades más frecuentes)', 'Hipertensión'],
  ['inf_habitantes', 'artritis!=""', '(Enfermedades más frecuentes)', 'Artritis'],
  ['inf_habitantes', 'asma!=""', '(Enfermedades más frecuentes)', 'Asma'],
  ['inf_habitantes', 'epilepsia!=""', '(Enfermedades más frecuentes)', 'Epilepsia'],
  ['inf_habitantes', 'linfoma!=""', '(Enfermedades más frecuentes)', 'Linfoma'],
  ['inf_habitantes', 'paralisis!=""', '(Enfermedades más frecuentes)', 'Parálisis'],
  ['inf_habitantes', 'enf_cardiaca!=""', '(Enfermedades más frecuentes)', 'E. Cardiaca'],
  ['inf_habitantes', 'cancer!=""', '(Enfermedades más frecuentes)', 'Cancer'],
  ['inf_habitantes', 'mesa_tecnica_agua="SI"', '(Org. PP)', 'MT de agua'],
  ['inf_habitantes', 'mesa_tecnica_telecomunicaciones="SI"', '(Org. PP)', 'MT de telecomunicaciones'],
  ['inf_habitantes', 'sala_bnbt="SI"', '(Org. PP)', 'Sala BNBT'],
  ['inf_habitantes', 'concejo_comunal!=""', '(Org. PP)', 'Consejo comunal'],
  ['inf_habitantes', 'raas!=""', '(Org. PP)', 'Raas'],
  ['inf_habitantes', 'clap!=""', '(Org. PP)', 'Clap'],
  ['inf_habitantes', 'ubch!=""', '(Org. PP)', 'Ubch'],
  ['inf_habitantes', 'milicia!=""', '(Org. PP)', 'Miliciano'],
  ['inf_habitantes', 'promotores_comunitarios!=""', '(Org. PP)', 'Promotores C.'],
  ['inf_habitantes', 'ffm!=""', '(Org. PP)', 'FFM'],
  ['inf_habitantes', 'msv!=""', '(Org. PP)', 'MSV'],
  ['inf_habitantes', 'creencia_reliosa="Creyente Sin Religion"', '(Religion)', 'Creyente Sin Religion'],
  ['inf_habitantes', 'creencia_reliosa="Adventista"', '(Religion)', 'Adventista'],
  ['inf_habitantes', 'creencia_reliosa="Bahai"', '(Religion)', 'Bahai'],
  ['inf_habitantes', 'creencia_reliosa="Católico"', '(Religion)', 'Católico'],
  ['inf_habitantes', 'creencia_reliosa="Budissta"', '(Religion)', 'Budissta'],
  ['inf_habitantes', 'creencia_reliosa="Espiritista"', '(Religion)', 'Espiritista'],
  ['inf_habitantes', 'creencia_reliosa="Evangélico"', '(Religion)', 'Evangélico'],
  ['inf_habitantes', 'creencia_reliosa="Islamico"', '(Religion)', 'Islamico'],
  ['inf_habitantes', 'creencia_reliosa="Gnóstico"', '(Religion)', 'Gnóstico'],
  ['inf_habitantes', 'creencia_reliosa="Judío"', '(Religion)', 'Judío'],
  ['inf_habitantes', 'creencia_reliosa="Mason"', '(Religion)', 'Mason'],
  ['inf_habitantes', 'creencia_reliosa="Palero"', '(Religion)', 'Palero'],
  ['inf_habitantes', 'creencia_reliosa="Santero"', '(Religion)', 'Santero'],
  ['inf_habitantes', 'creencia_reliosa="Testigo de Jehova"', '(Religion)', 'Testigo de Jehova'],
  ['inf_habitantes', 'creencia_reliosa="Ninguna (Agnostico)"', '(Religion)', 'Ninguna (Agnostico)'],
  ['inf_habitantes', 'creencia_reliosa="Ninguna (Ateo)"', '(Religion)', 'Ninguna (Ateo)'],
  ['inf_habitantes', 'pueblo_indigena="Baniva"', '(Pueblo indigena)', 'Baniva'],
  ['inf_habitantes', 'pueblo_indigena="Bare"', '(Pueblo indigena)', 'Bare'],
  ['inf_habitantes', 'pueblo_indigena="Cubeo"', '(Pueblo indigena)', 'Cubeo'],
  ['inf_habitantes', 'pueblo_indigena="Curripaco"', '(Pueblo indigena)', 'Curripaco'],
  ['inf_habitantes', 'pueblo_indigena="Eñapa"', '(Pueblo indigena)', 'Eñapa'],
  ['inf_habitantes', 'pueblo_indigena="Guanano"', '(Pueblo indigena)', 'Guanano'],
  ['inf_habitantes', 'pueblo_indigena="Hotti"', '(Pueblo indigena)', 'Hotti'],
  ['inf_habitantes', 'pueblo_indigena="Inga"', '(Pueblo indigena)', 'Inga'],
  ['inf_habitantes', 'pueblo_indigena="Jivi"', '(Pueblo indigena)', 'Jivi'],
  ['inf_habitantes', 'pueblo_indigena="Piapoco"', '(Pueblo indigena)', 'Piapoco'],
  ['inf_habitantes', 'pueblo_indigena="Piaroa"', '(Pueblo indigena)', 'Piaroa'],
  ['inf_habitantes', 'pueblo_indigena="Puinave"', '(Pueblo indigena)', 'Puinave'],
  ['inf_habitantes', 'pueblo_indigena="Saliva"', '(Pueblo indigena)', 'Saliva'],
  ['inf_habitantes', 'pueblo_indigena="Sanema"', '(Pueblo indigena)', 'Sanema'],
  ['inf_habitantes', 'pueblo_indigena="Warequena"', '(Pueblo indigena)', 'Warequena'],
  ['inf_habitantes', 'pueblo_indigena="Yabarana"', '(Pueblo indigena)', 'Yabarana'],
  ['inf_habitantes', 'pueblo_indigena="Yanomami"', '(Pueblo indigena)', 'Yanomami'],
  ['inf_habitantes', 'pueblo_indigena="Yavitero"', '(Pueblo indigena)', 'Yavitero'],
  ['inf_habitantes', 'pueblo_indigena="Yecuana"', '(Pueblo indigena)', 'Yecuana'],
  ['inf_habitantes', 'pueblo_indigena="Yeral"', '(Pueblo indigena)', 'Yeral'],
 
  ['inf_habitantes', 'cancer="Cabeza y Cuello"', '(Cancer)', 'Cabeza y Cuello'],
  ['inf_habitantes', 'cancer="Cerebro"', '(Cancer)', 'Cerebro'],
  ['inf_habitantes', 'cancer="Colorectal"', '(Cancer)', 'Colorectal'],
  ['inf_habitantes', 'cancer="Cuello Uterino"', '(Cancer)', 'Cuello Uterino'],
  ['inf_habitantes', 'cancer="Endometrio"', '(Cancer)', 'Endometrio'],
  ['inf_habitantes', 'cancer="Estomago"', '(Cancer)', 'Estomago'],
  ['inf_habitantes', 'cancer="Hepatico"', '(Cancer)', 'Hepatico'],
  ['inf_habitantes', 'cancer="Higado"', '(Cancer)', 'Higado'],
  ['inf_habitantes', 'cancer="Huesos"', '(Cancer)', 'Huesos'],
  ['inf_habitantes', 'cancer="Leucemia"', '(Cancer)', 'Leucemia'],
  ['inf_habitantes', 'cancer="Melnoma"', '(Cancer)', 'Melnoma'],
  ['inf_habitantes', 'cancer="Mama"', '(Cancer)', 'Mama'],
  ['inf_habitantes', 'cancer="Prostata"', '(Cancer)', 'Prostata'],

  ['inf_habitantes', 'cancer="Cabeza y Cuello" AND sexo="Femenino"', '(Cancer - Femenino)', 'Cabeza y Cuello', 'F'],
  ['inf_habitantes', 'cancer="Cerebro" AND sexo="Femenino"', '(Cancer - Femenino)', 'Cerebro', 'F'],
  ['inf_habitantes', 'cancer="Colorectal" AND sexo="Femenino"', '(Cancer - Femenino)', 'Colorectal', 'F'],
  ['inf_habitantes', 'cancer="Cuello Uterino" AND sexo="Femenino"', '(Cancer - Femenino)', 'Cuello Uterino', 'F'],
  ['inf_habitantes', 'cancer="Endometrio" AND sexo="Femenino"', '(Cancer - Femenino)', 'Endometrio', 'F'],
  ['inf_habitantes', 'cancer="Estomago" AND sexo="Femenino"', '(Cancer - Femenino)', 'Estomago', 'F'],
  ['inf_habitantes', 'cancer="Hepatico" AND sexo="Femenino"', '(Cancer - Femenino)', 'Hepatico', 'F'],
  ['inf_habitantes', 'cancer="Higado" AND sexo="Femenino"', '(Cancer - Femenino)', 'Higado', 'F'],
  ['inf_habitantes', 'cancer="Huesos" AND sexo="Femenino"', '(Cancer - Femenino)', 'Huesos', 'F'],
  ['inf_habitantes', 'cancer="Leucemia" AND sexo="Femenino"', '(Cancer - Femenino)', 'Leucemia', 'F'],
  ['inf_habitantes', 'cancer="Mama" AND sexo="Femenino"', '(Cancer - Femenino)', 'Mama', 'F'],
  ['inf_habitantes', 'cancer="Melnoma" AND sexo="Femenino"', '(Cancer - Femenino)', 'Melnoma', 'F'],

  ['inf_habitantes', 'cancer="Cabeza y Cuello" AND sexo="Masculino"', '(Cancer - Masculino)', 'Cabeza y Cuello'],
  ['inf_habitantes', 'cancer="Cerebro" AND sexo="Masculino"', '(Cancer - Masculino)', 'Cerebro'],
  ['inf_habitantes', 'cancer="Colorectal" AND sexo="Masculino"', '(Cancer - Masculino)', 'Colorectal'],
  ['inf_habitantes', 'cancer="Estomago" AND sexo="Masculino"', '(Cancer - Masculino)', 'Estomago'],
  ['inf_habitantes', 'cancer="Hepatico" AND sexo="Masculino"', '(Cancer - Masculino)', 'Hepatico'],
  ['inf_habitantes', 'cancer="Higado" AND sexo="Masculino"', '(Cancer - Masculino)', 'Higado'],
  ['inf_habitantes', 'cancer="Huesos" AND sexo="Masculino"', '(Cancer - Masculino)', 'Huesos'],
  ['inf_habitantes', 'cancer="Leucemia" AND sexo="Masculino"', '(Cancer - Masculino)', 'Leucemia'],
  ['inf_habitantes', 'cancer="Melnoma" AND sexo="Masculino"', '(Cancer - Masculino)', 'Melnoma'],
  ['inf_habitantes', 'cancer="Prostata" AND sexo="Masculino"', '(Cancer - Masculino)', 'Prostata'],
 
  ['inf_habitantes', 'discapacidad!=""', '(Discapacidad)', 'Alguna discapacidad'],
  ['inf_habitantes', 'discapacidad="Fisica"', '(Discapacidad)', 'Fisica'],
  ['inf_habitantes', 'discapacidad="Auditiva"', '(Discapacidad)', 'Auditiva'],
  ['inf_habitantes', 'discapacidad="Visual"', '(Discapacidad)', 'Visual'],
  ['inf_habitantes', 'discapacidad="Vohabla"', '(Discapacidad)', 'Vohabla'],
  ['inf_habitantes', 'discapacidad="Intelectual"', '(Discapacidad)', 'Intelectual'],
  ['inf_habitantes', 'discapacidad="Mental"', '(Discapacidad)', 'Mental'],
  ['inf_habitantes', 'discapacidad="Autismo o Asperger"', '(Discapacidad)', 'Autismo o Asperge'],
  ['inf_habitantes', 'educacion="Media General Incompleto"', '(Educación)', 'Media General Incompleto'],
  ['inf_habitantes', 'educacion="Inicial"', '(Educación)', 'Inicial'],
  ['inf_habitantes', 'educacion="Basica"', '(Educación)', 'Basica'],
  ['inf_habitantes', 'educacion="Sin estudio"', '(Educación)', 'Sin estudio'],
  ['inf_habitantes', 'educacion="Especialización"', '(Educación)', 'Especialización'],
  ['inf_habitantes', 'educacion="Misión Ribas"', '(Educación)', 'Misión Ribas'],
  ['inf_habitantes', 'educacion="Misión Robinson"', '(Educación)', 'Misión Robinson'],
  ['inf_habitantes', 'educacion="Misión Sucre"', '(Educación)', 'Misión Sucre'],
  ['inf_habitantes', 'educacion="No Escolarizado Inicial a Media General"', '(Educación)', 'No Escolarizado Inicial a Media General'],
  ['inf_habitantes', 'educacion="Postgrados"', '(Educación)', 'Postgrados'],
  ['inf_habitantes', 'educacion="Postgrado Incompleto"', '(Educación)', 'Postgrado Incompleto'],
  ['inf_habitantes', 'educacion="Universitario"', '(Educación)', 'Universitario'],
  ['inf_habitantes', 'educacion="Universitario Incompleto"', '(Educación)', 'Universitario Incompleto'],
  ['inf_habitantes', 'realiza_actividad_cultural="Artes Plasticas"', '(Actividad cultural)', 'Artes Plasticas'],
  ['inf_habitantes', 'realiza_actividad_cultural="Baile"', '(Actividad cultural)', 'Baile'],
  ['inf_habitantes', 'realiza_actividad_cultural="Cuenta Cuentos"', '(Actividad cultural)', 'Cuenta Cuentos'],
  ['inf_habitantes', 'realiza_actividad_cultural="Danza"', '(Actividad cultural)', 'Danza'],
  ['inf_habitantes', 'realiza_actividad_cultural="Musica"', '(Actividad cultural)', 'Musica'],
  ['inf_habitantes', 'realiza_actividad_cultural="Pintura"', '(Actividad cultural)', 'Pintura'],
  ['inf_habitantes', 'realiza_actividad_cultural="Teatro"', '(Actividad cultural)', 'Teatro'],
  ['inf_habitantes', 'profesion="Abogado"', '(Profesón)', 'Abogado'],
  ['inf_habitantes', 'profesion="Administrador"', '(Profesón)', 'Administrador'],
  ['inf_habitantes', 'profesion="Arquitecto"', '(Profesón)', 'Arquitecto'],
  ['inf_habitantes', 'profesion="Contador"', '(Profesón)', 'Contador'],
  ['inf_habitantes', 'profesion="Educador"', '(Profesón)', 'Educador'],
  ['inf_habitantes', 'profesion="Enfermeros"', '(Profesón)', 'Enfermeros'],
  ['inf_habitantes', 'profesion="Gestion"', '(Profesón)', 'Gestion'],
  ['inf_habitantes', 'profesion="Ingeniero"', '(Profesón)', 'Ingeniero'],
  ['inf_habitantes', 'profesion="Medico"', '(Profesón)', 'Medico'],
  ['inf_habitantes', 'profesion="Odontologo"', '(Profesón)', 'Odontologo'],
  ['inf_habitantes', 'ocupacion="Desempleado"', '(Ocupación)', 'Desempleado'],
  ['inf_habitantes', 'ocupacion="Empleado"', '(Ocupación)', 'Empleado'],
  ['inf_habitantes', 'ocupacion="Estudiante"', '(Ocupación)', 'Estudiante'],
  ['inf_habitantes', 'ocupacion="Obrero"', '(Ocupación)', 'Obrero'],
  ['inf_habitantes', 'ocupacion="Oficios del Hogar"', '(Ocupación)', 'Oficios del Hogar'],
  ['inf_habitantes', 'ocupacion="Trabajador por Cuenta Propia (Formal)"', '(Ocupación)', 'Cuenta Propia (Formal)'],
  ['inf_habitantes', 'ocupacion="Trabajador por Cuenta Propia (Informal)"', '(Ocupación)', 'Cuenta Propia (Informal)'],
  ['inf_habitantes', 'pertenece_cuerpo_seguridad_gestion_riesgo="Bomberos"', '(Cuerpos de Seguridad y Gestion de Riesgo)', 'Bomberos'],
  ['inf_habitantes', 'pertenece_cuerpo_seguridad_gestion_riesgo="CICPC"', '(Cuerpos de Seguridad y Gestion de Riesgo)', 'CICPC'],
  ['inf_habitantes', 'pertenece_cuerpo_seguridad_gestion_riesgo="Armada"', '(Cuerpos de Seguridad y Gestion de Riesgo)', 'Armada'],
  ['inf_habitantes', 'pertenece_cuerpo_seguridad_gestion_riesgo="Aviación"', '(Cuerpos de Seguridad y Gestion de Riesgo)', 'Aviación'],
  ['inf_habitantes', 'pertenece_cuerpo_seguridad_gestion_riesgo="Ejercito"', '(Cuerpos de Seguridad y Gestion de Riesgo)', 'Ejercito'],
  ['inf_habitantes', 'pertenece_cuerpo_seguridad_gestion_riesgo="Guardia Nacional"', '(Cuerpos de Seguridad y Gestion de Riesgo)', 'Guardia Nacional'],
  ['inf_habitantes', 'pertenece_cuerpo_seguridad_gestion_riesgo="Milicia"', '(Cuerpos de Seguridad y Gestion de Riesgo)', 'Milicia'],
  ['inf_habitantes', 'pertenece_cuerpo_seguridad_gestion_riesgo="Policia Estadal"', '(Cuerpos de Seguridad y Gestion de Riesgo)', 'Policia Estadal'],
  ['inf_habitantes', 'pertenece_cuerpo_seguridad_gestion_riesgo="Policia Municipa"', '(Cuerpos de Seguridad y Gestion de Riesgo)', 'Policia Municipa'],
  ['inf_habitantes', 'pertenece_cuerpo_seguridad_gestion_riesgo="Policia Nacional"', '(Cuerpos de Seguridad y Gestion de Riesgo)', 'Policia Nacional'],
  ['inf_habitantes', 'pertenece_cuerpo_seguridad_gestion_riesgo="Protección Civil"', '(Cuerpos de Seguridad y Gestion de Riesgo)', 'Protección Civil'],
  ['inf_habitantes', 'pertenece_cuerpo_seguridad_gestion_riesgo="SEBIN"', '(Cuerpos de Seguridad y Gestion de Riesgo)', 'SEBIN'],


  ['inf_habitantes', 'diabetico!="" AND sexo="Masculino"', '(Enfermedades más frecuentes - Masculino)', 'Diabetes'],
  ['inf_habitantes', 'hipertenso!="" AND sexo="Masculino"', '(Enfermedades más frecuentes - Masculino)', 'Hipertensión'],
  ['inf_habitantes', 'artritis!="" AND sexo="Masculino"', '(Enfermedades más frecuentes - Masculino)', 'Artritis'],
  ['inf_habitantes', 'epilepsia!="" AND sexo="Masculino"', '(Enfermedades más frecuentes - Masculino)', 'Epilepsia'],
  ['inf_habitantes', 'asma!="" AND sexo="Masculino"', '(Enfermedades más frecuentes - Masculino)', 'Asma'],
  ['inf_habitantes', 'linfoma!="" AND sexo="Masculino"', '(Enfermedades más frecuentes - Masculino)', 'Linfoma'],
  ['inf_habitantes', 'paralisis!="" AND sexo="Masculino"', '(Enfermedades más frecuentes - Masculino)', 'Parálisis'],
  ['inf_habitantes', 'enf_cardiaca!="" AND sexo="Masculino"', '(Enfermedades más frecuentes - Masculino)', 'E. Cardiaca'],
  ['inf_habitantes', 'enf_renal!="" AND sexo="Masculino"', '(Enfermedades más frecuentes - Masculino)', 'E. renal'],
  ['inf_habitantes', 'cancer!="" AND sexo="Masculino"', '(Enfermedades más frecuentes - Masculino)', 'Cancer'],

  ['inf_habitantes', 'diabetico!="" AND sexo="Femenino"', '(Enfermedades más frecuentes - Femenino)', 'Diabetes', 'F'],
  ['inf_habitantes', 'hipertenso!="" AND sexo="Femenino"', '(Enfermedades más frecuentes - Femenino)', 'Hipertensión', 'F'],
  ['inf_habitantes', 'artritis!="" AND sexo="Femenino"', '(Enfermedades más frecuentes - Femenino)', 'Artritis', 'F'],
  ['inf_habitantes', 'asma!="" AND sexo="Femenino"', '(Enfermedades más frecuentes - Femenino)', 'Epilepsia', 'F'],
  ['inf_habitantes', 'epilepsia!="" AND sexo="Femenino"', '(Enfermedades más frecuentes - Femenino)', 'Asma', 'F'],
  ['inf_habitantes', 'linfoma!="" AND sexo="Femenino"', '(Enfermedades más frecuentes - Femenino)', 'Linfoma', 'F'],
  ['inf_habitantes', 'paralisis!="" AND sexo="Femenino"', '(Enfermedades más frecuentes - Femenino)', 'Parálisis', 'F'],
  ['inf_habitantes', 'enf_cardiaca!="" AND sexo="Femenino"', '(Enfermedades más frecuentes - Femenino)', 'E. Cardiaca', 'F'],
  ['inf_habitantes', 'enf_renal!="" AND sexo="Femenino"', '(Enfermedades más frecuentes - Femenino)', 'E. renal', 'F'],
  ['inf_habitantes', 'cancer!="" AND sexo="Femenino"', '(Enfermedades más frecuentes - Femenino)', 'Cancer', 'F'],

  ['inf_habitantes', 'actividad_agricola="Patio Productivo"', '(Actividad agricola)', 'Patio Productivo'],
  ['inf_habitantes', 'actividad_agricola="conuco"', '(Actividad agricola)', 'Conuco'],
  ['inf_habitantes', 'actividad_agricola="Pesca"', '(Actividad agricola)', 'Pesca'],
  ['inf_habitantes', 'actividad_agricola="acuicultura"', '(Actividad agricola)', 'acuicultura'],
  ['inf_habitantes', 'actividad_agricola="Cria de Animales de Consumo"', '(Actividad agricola)', 'Cria de Animales de Consumo'],
  ['inf_habitantes', 'instancia_laboral="Publico Municipal"', '(Instancia Laboral)', 'Publico Municipal'],
  ['inf_habitantes', 'instancia_laboral="Publico Regional"', '(Instancia Laboral)', 'Publico Regional'],
  ['inf_habitantes', 'instancia_laboral="Publico Nacional"', '(Instancia Laboral)', 'Publico Nacional'],

  ['inf_habitantes', 'embarazada="SI"', '(Embarazadas)', 'Embarazadas', 'F'], // femenino
  ['inf_habitantes', 'embarazada_alto_riesgo="SI"', '(Embarazadas)', 'Embarazadas (Riesgo)', 'F'], // femenino
  ['inf_habitantes', 'madre_lactante="SI"', '(Protección social)', 'Madres lactantes', 'F'], // femenino
  ['inf_habitantes', 'bono_lactancia="SI"', '(Protección social)', 'Bono lactancia', 'F'], // femenino
  ['inf_habitantes', 'parto_humanizado="SI"', '(Protección social)', 'Parto Humanizado', 'F'], // femenino

  ['inf_habitantes', 'recibe_bono_jose_g!=""', '(Protección social)', 'José Gregorio Hernández'],
  ['inf_habitantes', 'requiere_ayuda!=""', '(Protección social)', 'Requiere ayuda técnica (Discapacidad)'],
  ['inf_habitantes', 'pension="SI"', '(Protección social)', 'Amor mayor y pensionados'],
  ['inf_habitantes', 'deficit_nutricional="SI"', '(Protección social)', 'Deficit nutricional'],
  ['inf_habitantes', 'combo_inn="SI"', '(Protección social)', 'Combo INN'],
  ['inf_habitantes', 'hogares_de_la_patria="SI"', '(Protección social)', 'Hogares de la patria'],

);
?>